name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.0]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies 
        run: npm install
      
      - name: Build
        working-directory: ./
        run: npm run gh-build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist/szokalski
